### ISSUE TITLE
Errors on Build

### ISSUE THREAD

**Issue by Correlander** [Joy-less/TCPMaid#2]
There is a 99% chance these errors stem from my own failures. It's 5am and the issues likely stem from the user (me).
![image](https://github.com/Joy-less/TCPMaid/assets/53982700/02f26ab2-011e-4d52-96be-17bf431569f1)
I have the MemoryPack dependency package installed. I have .NET 8.0 SDK installed. I have visual studio 2022 with the .NET Desktop Development Workload. I have my editor in Godot set to Visual Studio, it properly opens up with the project and everything. I installed the addon in-editor through the Asset Library, it installed all the files underneath addons/TCPMaid. Did I miss a step?

**Comment by Joy-less** [comment]
Apologies for the inconvenience. While the TCPMaid source is available in the Godot asset library, it's not designed to be dropped into a project (because of project settings). You should install it with NuGet.

**Comment by Correlander** [comment]
Ah, okay, that makes a lot more sense. I was curious why there were assets for the icon etc. if it's only dropped into project files, makes sense now though. I really appreciate the quick reply, everything works now.

**Comment by Correlander** [comment]
Ah, okay, that makes a lot more sense. I was curious why there were assets for the icon etc. if it's only dropped into project files, makes sense now though. I really appreciate the quick reply, everything works now.
